import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#A6D3F2',
    paddingTop: 50,
    alignItems: 'center',
  },
  headerBox: {
    width: 229,
    height: 46,
    backgroundColor: '#6ACBFF',
    borderRadius: 82,
    borderWidth: 1,
    borderColor: '#3700DD',
    shadowColor: 'rgba(0, 2, 98, 0.25)',
    shadowOffset: { width: 4, height: 7 },
    shadowRadius: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 40,
    fontFamily: 'Just Another Hand',
    color: '#000',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginTop: 30,
    gap: 20,
  },
  card: {
    width: 165,
    height: 175,
    backgroundColor: '#946EFF',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  image: {
    width: 100,
    height: 100,
  },
  label: {
    fontSize: 30,
    fontFamily: 'Just Another Hand',
    color: '#000',
    marginTop: 10,
  },
  helpButton: {
    marginTop: 30,
    width: 118,
    height: 40,
    backgroundColor: '#6ACBFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3700DD',
    shadowColor: 'rgba(0, 2, 98, 1)',
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  helpText: {
    fontSize: 29,
    fontFamily: 'Just Another Hand',
    color: '#000',
  },
});
